name: "port:dev_docker"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=port
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - port_network
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' --quiet" ]
      interval: 1s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../
      dockerfile: infra/dev.Dockerfile
    working_dir: /app/backend
    ports: ["3000:3000"]
    environment: ["NODE_ENV"]
    volumes: ["../:/app/"]
    networks: ["port_network"]
    command: "pnpm run start:dev_docker"
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ../
      dockerfile: infra/dev.Dockerfile
    working_dir: /app/frontend
    environment: ["NODE_ENV"]
    volumes: ["../:/app/"]
    networks: ["port_network"]
    command: "pnpm run dev"


volumes:
  mongodb_data:

networks:
  port_network:
    driver: bridge