name: "port:dev"

services:
  mongodb:
    image: mongo:latest
    container_name: port_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=port
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:

